//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marisfrolg.Fee.EnterpriceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://marisfrolg.com/", ConfigurationName="EnterpriceService.MfWeiXinEmpServiceSoap")]
    public interface MfWeiXinEmpServiceSoap {
        
        // CODEGEN: 命名空间 http://marisfrolg.com/ 的元素名称 identify 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marisfrolg.com/CreateMenu", ReplyAction="*")]
        Marisfrolg.Fee.EnterpriceService.CreateMenuResponse CreateMenu(Marisfrolg.Fee.EnterpriceService.CreateMenuRequest request);
        
        // CODEGEN: 命名空间 http://marisfrolg.com/ 的元素名称 identify 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marisfrolg.com/SendMessage", ReplyAction="*")]
        Marisfrolg.Fee.EnterpriceService.SendMessageResponse SendMessage(Marisfrolg.Fee.EnterpriceService.SendMessageRequest request);
        
        // CODEGEN: 命名空间 http://marisfrolg.com/ 的元素名称 identify 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marisfrolg.com/GetUserId", ReplyAction="*")]
        Marisfrolg.Fee.EnterpriceService.GetUserIdResponse GetUserId(Marisfrolg.Fee.EnterpriceService.GetUserIdRequest request);
        
        // CODEGEN: 命名空间 http://marisfrolg.com/ 的元素名称 identify 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marisfrolg.com/GetOpenid", ReplyAction="*")]
        Marisfrolg.Fee.EnterpriceService.GetOpenidResponse GetOpenid(Marisfrolg.Fee.EnterpriceService.GetOpenidRequest request);
        
        // CODEGEN: 命名空间 http://marisfrolg.com/ 的元素名称 identify 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marisfrolg.com/GetconvertUserId", ReplyAction="*")]
        Marisfrolg.Fee.EnterpriceService.GetconvertUserIdResponse GetconvertUserId(Marisfrolg.Fee.EnterpriceService.GetconvertUserIdRequest request);
        
        // CODEGEN: 命名空间 http://marisfrolg.com/ 的元素名称 identify 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marisfrolg.com/GetUserInfo", ReplyAction="*")]
        Marisfrolg.Fee.EnterpriceService.GetUserInfoResponse GetUserInfo(Marisfrolg.Fee.EnterpriceService.GetUserInfoRequest request);
        
        // CODEGEN: 命名空间 http://marisfrolg.com/ 的元素名称 identify 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marisfrolg.com/GetdepartmentList", ReplyAction="*")]
        Marisfrolg.Fee.EnterpriceService.GetdepartmentListResponse GetdepartmentList(Marisfrolg.Fee.EnterpriceService.GetdepartmentListRequest request);
        
        // CODEGEN: 命名空间 http://marisfrolg.com/ 的元素名称 identify 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marisfrolg.com/Createdepartment", ReplyAction="*")]
        Marisfrolg.Fee.EnterpriceService.CreatedepartmentResponse Createdepartment(Marisfrolg.Fee.EnterpriceService.CreatedepartmentRequest request);
        
        // CODEGEN: 命名空间 http://marisfrolg.com/ 的元素名称 identify 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marisfrolg.com/Updatedepartment", ReplyAction="*")]
        Marisfrolg.Fee.EnterpriceService.UpdatedepartmentResponse Updatedepartment(Marisfrolg.Fee.EnterpriceService.UpdatedepartmentRequest request);
        
        // CODEGEN: 命名空间 http://marisfrolg.com/ 的元素名称 identify 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marisfrolg.com/Deletedepartment", ReplyAction="*")]
        Marisfrolg.Fee.EnterpriceService.DeletedepartmentResponse Deletedepartment(Marisfrolg.Fee.EnterpriceService.DeletedepartmentRequest request);
        
        // CODEGEN: 命名空间 http://marisfrolg.com/ 的元素名称 identify 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marisfrolg.com/CreateMember", ReplyAction="*")]
        Marisfrolg.Fee.EnterpriceService.CreateMemberResponse CreateMember(Marisfrolg.Fee.EnterpriceService.CreateMemberRequest request);
        
        // CODEGEN: 命名空间 http://marisfrolg.com/ 的元素名称 identify 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marisfrolg.com/UpdateMember", ReplyAction="*")]
        Marisfrolg.Fee.EnterpriceService.UpdateMemberResponse UpdateMember(Marisfrolg.Fee.EnterpriceService.UpdateMemberRequest request);
        
        // CODEGEN: 命名空间 http://marisfrolg.com/ 的元素名称 identify 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marisfrolg.com/DeleteMember", ReplyAction="*")]
        Marisfrolg.Fee.EnterpriceService.DeleteMemberResponse DeleteMember(Marisfrolg.Fee.EnterpriceService.DeleteMemberRequest request);
        
        // CODEGEN: 命名空间 http://marisfrolg.com/ 的元素名称 identify 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marisfrolg.com/BatchDeleteMember", ReplyAction="*")]
        Marisfrolg.Fee.EnterpriceService.BatchDeleteMemberResponse BatchDeleteMember(Marisfrolg.Fee.EnterpriceService.BatchDeleteMemberRequest request);
        
        // CODEGEN: 命名空间 http://marisfrolg.com/ 的元素名称 identify 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marisfrolg.com/GetuseridInfo", ReplyAction="*")]
        Marisfrolg.Fee.EnterpriceService.GetuseridInfoResponse GetuseridInfo(Marisfrolg.Fee.EnterpriceService.GetuseridInfoRequest request);
        
        // CODEGEN: 命名空间 http://marisfrolg.com/ 的元素名称 identify 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marisfrolg.com/getdepartmenuser", ReplyAction="*")]
        Marisfrolg.Fee.EnterpriceService.getdepartmenuserResponse getdepartmenuser(Marisfrolg.Fee.EnterpriceService.getdepartmenuserRequest request);
        
        // CODEGEN: 命名空间 http://marisfrolg.com/ 的元素名称 identify 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marisfrolg.com/getdepartmenuserinfo", ReplyAction="*")]
        Marisfrolg.Fee.EnterpriceService.getdepartmenuserinfoResponse getdepartmenuserinfo(Marisfrolg.Fee.EnterpriceService.getdepartmenuserinfoRequest request);
        
        // CODEGEN: 命名空间 http://marisfrolg.com/ 的元素名称 identify 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marisfrolg.com/Getticket", ReplyAction="*")]
        Marisfrolg.Fee.EnterpriceService.GetticketResponse Getticket(Marisfrolg.Fee.EnterpriceService.GetticketRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateMenuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateMenu", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.CreateMenuRequestBody Body;
        
        public CreateMenuRequest() {
        }
        
        public CreateMenuRequest(Marisfrolg.Fee.EnterpriceService.CreateMenuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class CreateMenuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identify;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int agentid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strMenu;
        
        public CreateMenuRequestBody() {
        }
        
        public CreateMenuRequestBody(string identify, int agentid, string strMenu) {
            this.identify = identify;
            this.agentid = agentid;
            this.strMenu = strMenu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateMenuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateMenuResponse", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.CreateMenuResponseBody Body;
        
        public CreateMenuResponse() {
        }
        
        public CreateMenuResponse(Marisfrolg.Fee.EnterpriceService.CreateMenuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class CreateMenuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CreateMenuResult;
        
        public CreateMenuResponseBody() {
        }
        
        public CreateMenuResponseBody(int CreateMenuResult) {
            this.CreateMenuResult = CreateMenuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(Marisfrolg.Fee.EnterpriceService.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identify;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int agentid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string touser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string content;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(string identify, int agentid, string touser, string content) {
            this.identify = identify;
            this.agentid = agentid;
            this.touser = touser;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(Marisfrolg.Fee.EnterpriceService.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class SendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendMessageResult;
        
        public SendMessageResponseBody() {
        }
        
        public SendMessageResponseBody(int SendMessageResult) {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserId", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.GetUserIdRequestBody Body;
        
        public GetUserIdRequest() {
        }
        
        public GetUserIdRequest(Marisfrolg.Fee.EnterpriceService.GetUserIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class GetUserIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identify;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userId;
        
        public GetUserIdRequestBody() {
        }
        
        public GetUserIdRequestBody(string identify, string code, string userId) {
            this.identify = identify;
            this.code = code;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserIdResponse", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.GetUserIdResponseBody Body;
        
        public GetUserIdResponse() {
        }
        
        public GetUserIdResponse(Marisfrolg.Fee.EnterpriceService.GetUserIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class GetUserIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetUserIdResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userId;
        
        public GetUserIdResponseBody() {
        }
        
        public GetUserIdResponseBody(int GetUserIdResult, string userId) {
            this.GetUserIdResult = GetUserIdResult;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOpenidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOpenid", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.GetOpenidRequestBody Body;
        
        public GetOpenidRequest() {
        }
        
        public GetOpenidRequest(Marisfrolg.Fee.EnterpriceService.GetOpenidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class GetOpenidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identify;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int agentid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string openid;
        
        public GetOpenidRequestBody() {
        }
        
        public GetOpenidRequestBody(string identify, string userId, int agentid, string openid) {
            this.identify = identify;
            this.userId = userId;
            this.agentid = agentid;
            this.openid = openid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOpenidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOpenidResponse", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.GetOpenidResponseBody Body;
        
        public GetOpenidResponse() {
        }
        
        public GetOpenidResponse(Marisfrolg.Fee.EnterpriceService.GetOpenidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class GetOpenidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetOpenidResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string openid;
        
        public GetOpenidResponseBody() {
        }
        
        public GetOpenidResponseBody(int GetOpenidResult, string openid) {
            this.GetOpenidResult = GetOpenidResult;
            this.openid = openid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetconvertUserIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetconvertUserId", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.GetconvertUserIdRequestBody Body;
        
        public GetconvertUserIdRequest() {
        }
        
        public GetconvertUserIdRequest(Marisfrolg.Fee.EnterpriceService.GetconvertUserIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class GetconvertUserIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identify;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string openid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userId;
        
        public GetconvertUserIdRequestBody() {
        }
        
        public GetconvertUserIdRequestBody(string identify, string openid, string userId) {
            this.identify = identify;
            this.openid = openid;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetconvertUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetconvertUserIdResponse", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.GetconvertUserIdResponseBody Body;
        
        public GetconvertUserIdResponse() {
        }
        
        public GetconvertUserIdResponse(Marisfrolg.Fee.EnterpriceService.GetconvertUserIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class GetconvertUserIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetconvertUserIdResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userId;
        
        public GetconvertUserIdResponseBody() {
        }
        
        public GetconvertUserIdResponseBody(int GetconvertUserIdResult, string userId) {
            this.GetconvertUserIdResult = GetconvertUserIdResult;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInfo", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.GetUserInfoRequestBody Body;
        
        public GetUserInfoRequest() {
        }
        
        public GetUserInfoRequest(Marisfrolg.Fee.EnterpriceService.GetUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class GetUserInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identify;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string auth_code;
        
        public GetUserInfoRequestBody() {
        }
        
        public GetUserInfoRequestBody(string identify, string auth_code) {
            this.identify = identify;
            this.auth_code = auth_code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInfoResponse", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.GetUserInfoResponseBody Body;
        
        public GetUserInfoResponse() {
        }
        
        public GetUserInfoResponse(Marisfrolg.Fee.EnterpriceService.GetUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class GetUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserInfoResult;
        
        public GetUserInfoResponseBody() {
        }
        
        public GetUserInfoResponseBody(string GetUserInfoResult) {
            this.GetUserInfoResult = GetUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetdepartmentListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetdepartmentList", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.GetdepartmentListRequestBody Body;
        
        public GetdepartmentListRequest() {
        }
        
        public GetdepartmentListRequest(Marisfrolg.Fee.EnterpriceService.GetdepartmentListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class GetdepartmentListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identify;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id;
        
        public GetdepartmentListRequestBody() {
        }
        
        public GetdepartmentListRequestBody(string identify, int id) {
            this.identify = identify;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetdepartmentListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetdepartmentListResponse", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.GetdepartmentListResponseBody Body;
        
        public GetdepartmentListResponse() {
        }
        
        public GetdepartmentListResponse(Marisfrolg.Fee.EnterpriceService.GetdepartmentListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class GetdepartmentListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetdepartmentListResult;
        
        public GetdepartmentListResponseBody() {
        }
        
        public GetdepartmentListResponseBody(string GetdepartmentListResult) {
            this.GetdepartmentListResult = GetdepartmentListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatedepartmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Createdepartment", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.CreatedepartmentRequestBody Body;
        
        public CreatedepartmentRequest() {
        }
        
        public CreatedepartmentRequest(Marisfrolg.Fee.EnterpriceService.CreatedepartmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class CreatedepartmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identify;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int parentid;
        
        public CreatedepartmentRequestBody() {
        }
        
        public CreatedepartmentRequestBody(string identify, string name, int parentid) {
            this.identify = identify;
            this.name = name;
            this.parentid = parentid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatedepartmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatedepartmentResponse", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.CreatedepartmentResponseBody Body;
        
        public CreatedepartmentResponse() {
        }
        
        public CreatedepartmentResponse(Marisfrolg.Fee.EnterpriceService.CreatedepartmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class CreatedepartmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CreatedepartmentResult;
        
        public CreatedepartmentResponseBody() {
        }
        
        public CreatedepartmentResponseBody(int CreatedepartmentResult) {
            this.CreatedepartmentResult = CreatedepartmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatedepartmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Updatedepartment", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.UpdatedepartmentRequestBody Body;
        
        public UpdatedepartmentRequest() {
        }
        
        public UpdatedepartmentRequest(Marisfrolg.Fee.EnterpriceService.UpdatedepartmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class UpdatedepartmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identify;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int parentid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int order;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int id;
        
        public UpdatedepartmentRequestBody() {
        }
        
        public UpdatedepartmentRequestBody(string identify, string name, int parentid, int order, int id) {
            this.identify = identify;
            this.name = name;
            this.parentid = parentid;
            this.order = order;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatedepartmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatedepartmentResponse", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.UpdatedepartmentResponseBody Body;
        
        public UpdatedepartmentResponse() {
        }
        
        public UpdatedepartmentResponse(Marisfrolg.Fee.EnterpriceService.UpdatedepartmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class UpdatedepartmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdatedepartmentResult;
        
        public UpdatedepartmentResponseBody() {
        }
        
        public UpdatedepartmentResponseBody(int UpdatedepartmentResult) {
            this.UpdatedepartmentResult = UpdatedepartmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletedepartmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Deletedepartment", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.DeletedepartmentRequestBody Body;
        
        public DeletedepartmentRequest() {
        }
        
        public DeletedepartmentRequest(Marisfrolg.Fee.EnterpriceService.DeletedepartmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class DeletedepartmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identify;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id;
        
        public DeletedepartmentRequestBody() {
        }
        
        public DeletedepartmentRequestBody(string identify, int id) {
            this.identify = identify;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletedepartmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletedepartmentResponse", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.DeletedepartmentResponseBody Body;
        
        public DeletedepartmentResponse() {
        }
        
        public DeletedepartmentResponse(Marisfrolg.Fee.EnterpriceService.DeletedepartmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class DeletedepartmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeletedepartmentResult;
        
        public DeletedepartmentResponseBody() {
        }
        
        public DeletedepartmentResponseBody(int DeletedepartmentResult) {
            this.DeletedepartmentResult = DeletedepartmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateMemberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateMember", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.CreateMemberRequestBody Body;
        
        public CreateMemberRequest() {
        }
        
        public CreateMemberRequest(Marisfrolg.Fee.EnterpriceService.CreateMemberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class CreateMemberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identify;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string department;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string position;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string weixinid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string avatar_mediaid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string extattr;
        
        public CreateMemberRequestBody() {
        }
        
        public CreateMemberRequestBody(string identify, string userid, string name, string department, string position, string mobile, string gender, string email, string weixinid, string avatar_mediaid, string extattr) {
            this.identify = identify;
            this.userid = userid;
            this.name = name;
            this.department = department;
            this.position = position;
            this.mobile = mobile;
            this.gender = gender;
            this.email = email;
            this.weixinid = weixinid;
            this.avatar_mediaid = avatar_mediaid;
            this.extattr = extattr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateMemberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateMemberResponse", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.CreateMemberResponseBody Body;
        
        public CreateMemberResponse() {
        }
        
        public CreateMemberResponse(Marisfrolg.Fee.EnterpriceService.CreateMemberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class CreateMemberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CreateMemberResult;
        
        public CreateMemberResponseBody() {
        }
        
        public CreateMemberResponseBody(int CreateMemberResult) {
            this.CreateMemberResult = CreateMemberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateMemberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateMember", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.UpdateMemberRequestBody Body;
        
        public UpdateMemberRequest() {
        }
        
        public UpdateMemberRequest(Marisfrolg.Fee.EnterpriceService.UpdateMemberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class UpdateMemberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identify;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string department;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string position;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string weixinid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string enable;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string avatar_mediaid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string extattr;
        
        public UpdateMemberRequestBody() {
        }
        
        public UpdateMemberRequestBody(string identify, string userid, string name, string department, string position, string mobile, string gender, string email, string weixinid, string enable, string avatar_mediaid, string extattr) {
            this.identify = identify;
            this.userid = userid;
            this.name = name;
            this.department = department;
            this.position = position;
            this.mobile = mobile;
            this.gender = gender;
            this.email = email;
            this.weixinid = weixinid;
            this.enable = enable;
            this.avatar_mediaid = avatar_mediaid;
            this.extattr = extattr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateMemberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateMemberResponse", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.UpdateMemberResponseBody Body;
        
        public UpdateMemberResponse() {
        }
        
        public UpdateMemberResponse(Marisfrolg.Fee.EnterpriceService.UpdateMemberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class UpdateMemberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateMemberResult;
        
        public UpdateMemberResponseBody() {
        }
        
        public UpdateMemberResponseBody(int UpdateMemberResult) {
            this.UpdateMemberResult = UpdateMemberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMemberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteMember", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.DeleteMemberRequestBody Body;
        
        public DeleteMemberRequest() {
        }
        
        public DeleteMemberRequest(Marisfrolg.Fee.EnterpriceService.DeleteMemberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class DeleteMemberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identify;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int userid;
        
        public DeleteMemberRequestBody() {
        }
        
        public DeleteMemberRequestBody(string identify, int userid) {
            this.identify = identify;
            this.userid = userid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMemberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteMemberResponse", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.DeleteMemberResponseBody Body;
        
        public DeleteMemberResponse() {
        }
        
        public DeleteMemberResponse(Marisfrolg.Fee.EnterpriceService.DeleteMemberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class DeleteMemberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeleteMemberResult;
        
        public DeleteMemberResponseBody() {
        }
        
        public DeleteMemberResponseBody(int DeleteMemberResult) {
            this.DeleteMemberResult = DeleteMemberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchDeleteMemberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchDeleteMember", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.BatchDeleteMemberRequestBody Body;
        
        public BatchDeleteMemberRequest() {
        }
        
        public BatchDeleteMemberRequest(Marisfrolg.Fee.EnterpriceService.BatchDeleteMemberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class BatchDeleteMemberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identify;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string useridlist;
        
        public BatchDeleteMemberRequestBody() {
        }
        
        public BatchDeleteMemberRequestBody(string identify, string useridlist) {
            this.identify = identify;
            this.useridlist = useridlist;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchDeleteMemberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchDeleteMemberResponse", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.BatchDeleteMemberResponseBody Body;
        
        public BatchDeleteMemberResponse() {
        }
        
        public BatchDeleteMemberResponse(Marisfrolg.Fee.EnterpriceService.BatchDeleteMemberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class BatchDeleteMemberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int BatchDeleteMemberResult;
        
        public BatchDeleteMemberResponseBody() {
        }
        
        public BatchDeleteMemberResponseBody(int BatchDeleteMemberResult) {
            this.BatchDeleteMemberResult = BatchDeleteMemberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetuseridInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetuseridInfo", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.GetuseridInfoRequestBody Body;
        
        public GetuseridInfoRequest() {
        }
        
        public GetuseridInfoRequest(Marisfrolg.Fee.EnterpriceService.GetuseridInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class GetuseridInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identify;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userid;
        
        public GetuseridInfoRequestBody() {
        }
        
        public GetuseridInfoRequestBody(string identify, string userid) {
            this.identify = identify;
            this.userid = userid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetuseridInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetuseridInfoResponse", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.GetuseridInfoResponseBody Body;
        
        public GetuseridInfoResponse() {
        }
        
        public GetuseridInfoResponse(Marisfrolg.Fee.EnterpriceService.GetuseridInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class GetuseridInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetuseridInfoResult;
        
        public GetuseridInfoResponseBody() {
        }
        
        public GetuseridInfoResponseBody(string GetuseridInfoResult) {
            this.GetuseridInfoResult = GetuseridInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getdepartmenuserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getdepartmenuser", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.getdepartmenuserRequestBody Body;
        
        public getdepartmenuserRequest() {
        }
        
        public getdepartmenuserRequest(Marisfrolg.Fee.EnterpriceService.getdepartmenuserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class getdepartmenuserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identify;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string department_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fetch_child;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string status;
        
        public getdepartmenuserRequestBody() {
        }
        
        public getdepartmenuserRequestBody(string identify, string department_id, string fetch_child, string status) {
            this.identify = identify;
            this.department_id = department_id;
            this.fetch_child = fetch_child;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getdepartmenuserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getdepartmenuserResponse", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.getdepartmenuserResponseBody Body;
        
        public getdepartmenuserResponse() {
        }
        
        public getdepartmenuserResponse(Marisfrolg.Fee.EnterpriceService.getdepartmenuserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class getdepartmenuserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getdepartmenuserResult;
        
        public getdepartmenuserResponseBody() {
        }
        
        public getdepartmenuserResponseBody(string getdepartmenuserResult) {
            this.getdepartmenuserResult = getdepartmenuserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getdepartmenuserinfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getdepartmenuserinfo", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.getdepartmenuserinfoRequestBody Body;
        
        public getdepartmenuserinfoRequest() {
        }
        
        public getdepartmenuserinfoRequest(Marisfrolg.Fee.EnterpriceService.getdepartmenuserinfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class getdepartmenuserinfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identify;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string department_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fetch_child;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string status;
        
        public getdepartmenuserinfoRequestBody() {
        }
        
        public getdepartmenuserinfoRequestBody(string identify, string department_id, string fetch_child, string status) {
            this.identify = identify;
            this.department_id = department_id;
            this.fetch_child = fetch_child;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getdepartmenuserinfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getdepartmenuserinfoResponse", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.getdepartmenuserinfoResponseBody Body;
        
        public getdepartmenuserinfoResponse() {
        }
        
        public getdepartmenuserinfoResponse(Marisfrolg.Fee.EnterpriceService.getdepartmenuserinfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class getdepartmenuserinfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getdepartmenuserinfoResult;
        
        public getdepartmenuserinfoResponseBody() {
        }
        
        public getdepartmenuserinfoResponseBody(string getdepartmenuserinfoResult) {
            this.getdepartmenuserinfoResult = getdepartmenuserinfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetticketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Getticket", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.GetticketRequestBody Body;
        
        public GetticketRequest() {
        }
        
        public GetticketRequest(Marisfrolg.Fee.EnterpriceService.GetticketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class GetticketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identify;
        
        public GetticketRequestBody() {
        }
        
        public GetticketRequestBody(string identify) {
            this.identify = identify;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetticketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetticketResponse", Namespace="http://marisfrolg.com/", Order=0)]
        public Marisfrolg.Fee.EnterpriceService.GetticketResponseBody Body;
        
        public GetticketResponse() {
        }
        
        public GetticketResponse(Marisfrolg.Fee.EnterpriceService.GetticketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marisfrolg.com/")]
    public partial class GetticketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetticketResult;
        
        public GetticketResponseBody() {
        }
        
        public GetticketResponseBody(string GetticketResult) {
            this.GetticketResult = GetticketResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MfWeiXinEmpServiceSoapChannel : Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MfWeiXinEmpServiceSoapClient : System.ServiceModel.ClientBase<Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap>, Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap {
        
        public MfWeiXinEmpServiceSoapClient() {
        }
        
        public MfWeiXinEmpServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MfWeiXinEmpServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MfWeiXinEmpServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MfWeiXinEmpServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Marisfrolg.Fee.EnterpriceService.CreateMenuResponse Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap.CreateMenu(Marisfrolg.Fee.EnterpriceService.CreateMenuRequest request) {
            return base.Channel.CreateMenu(request);
        }
        
        public int CreateMenu(string identify, int agentid, string strMenu) {
            Marisfrolg.Fee.EnterpriceService.CreateMenuRequest inValue = new Marisfrolg.Fee.EnterpriceService.CreateMenuRequest();
            inValue.Body = new Marisfrolg.Fee.EnterpriceService.CreateMenuRequestBody();
            inValue.Body.identify = identify;
            inValue.Body.agentid = agentid;
            inValue.Body.strMenu = strMenu;
            Marisfrolg.Fee.EnterpriceService.CreateMenuResponse retVal = ((Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap)(this)).CreateMenu(inValue);
            return retVal.Body.CreateMenuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Marisfrolg.Fee.EnterpriceService.SendMessageResponse Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap.SendMessage(Marisfrolg.Fee.EnterpriceService.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public int SendMessage(string identify, int agentid, string touser, string content) {
            Marisfrolg.Fee.EnterpriceService.SendMessageRequest inValue = new Marisfrolg.Fee.EnterpriceService.SendMessageRequest();
            inValue.Body = new Marisfrolg.Fee.EnterpriceService.SendMessageRequestBody();
            inValue.Body.identify = identify;
            inValue.Body.agentid = agentid;
            inValue.Body.touser = touser;
            inValue.Body.content = content;
            Marisfrolg.Fee.EnterpriceService.SendMessageResponse retVal = ((Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap)(this)).SendMessage(inValue);
            return retVal.Body.SendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Marisfrolg.Fee.EnterpriceService.GetUserIdResponse Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap.GetUserId(Marisfrolg.Fee.EnterpriceService.GetUserIdRequest request) {
            return base.Channel.GetUserId(request);
        }
        
        public int GetUserId(string identify, string code, ref string userId) {
            Marisfrolg.Fee.EnterpriceService.GetUserIdRequest inValue = new Marisfrolg.Fee.EnterpriceService.GetUserIdRequest();
            inValue.Body = new Marisfrolg.Fee.EnterpriceService.GetUserIdRequestBody();
            inValue.Body.identify = identify;
            inValue.Body.code = code;
            inValue.Body.userId = userId;
            Marisfrolg.Fee.EnterpriceService.GetUserIdResponse retVal = ((Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap)(this)).GetUserId(inValue);
            userId = retVal.Body.userId;
            return retVal.Body.GetUserIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Marisfrolg.Fee.EnterpriceService.GetOpenidResponse Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap.GetOpenid(Marisfrolg.Fee.EnterpriceService.GetOpenidRequest request) {
            return base.Channel.GetOpenid(request);
        }
        
        public int GetOpenid(string identify, string userId, int agentid, ref string openid) {
            Marisfrolg.Fee.EnterpriceService.GetOpenidRequest inValue = new Marisfrolg.Fee.EnterpriceService.GetOpenidRequest();
            inValue.Body = new Marisfrolg.Fee.EnterpriceService.GetOpenidRequestBody();
            inValue.Body.identify = identify;
            inValue.Body.userId = userId;
            inValue.Body.agentid = agentid;
            inValue.Body.openid = openid;
            Marisfrolg.Fee.EnterpriceService.GetOpenidResponse retVal = ((Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap)(this)).GetOpenid(inValue);
            openid = retVal.Body.openid;
            return retVal.Body.GetOpenidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Marisfrolg.Fee.EnterpriceService.GetconvertUserIdResponse Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap.GetconvertUserId(Marisfrolg.Fee.EnterpriceService.GetconvertUserIdRequest request) {
            return base.Channel.GetconvertUserId(request);
        }
        
        public int GetconvertUserId(string identify, string openid, ref string userId) {
            Marisfrolg.Fee.EnterpriceService.GetconvertUserIdRequest inValue = new Marisfrolg.Fee.EnterpriceService.GetconvertUserIdRequest();
            inValue.Body = new Marisfrolg.Fee.EnterpriceService.GetconvertUserIdRequestBody();
            inValue.Body.identify = identify;
            inValue.Body.openid = openid;
            inValue.Body.userId = userId;
            Marisfrolg.Fee.EnterpriceService.GetconvertUserIdResponse retVal = ((Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap)(this)).GetconvertUserId(inValue);
            userId = retVal.Body.userId;
            return retVal.Body.GetconvertUserIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Marisfrolg.Fee.EnterpriceService.GetUserInfoResponse Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap.GetUserInfo(Marisfrolg.Fee.EnterpriceService.GetUserInfoRequest request) {
            return base.Channel.GetUserInfo(request);
        }
        
        public string GetUserInfo(string identify, string auth_code) {
            Marisfrolg.Fee.EnterpriceService.GetUserInfoRequest inValue = new Marisfrolg.Fee.EnterpriceService.GetUserInfoRequest();
            inValue.Body = new Marisfrolg.Fee.EnterpriceService.GetUserInfoRequestBody();
            inValue.Body.identify = identify;
            inValue.Body.auth_code = auth_code;
            Marisfrolg.Fee.EnterpriceService.GetUserInfoResponse retVal = ((Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap)(this)).GetUserInfo(inValue);
            return retVal.Body.GetUserInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Marisfrolg.Fee.EnterpriceService.GetdepartmentListResponse Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap.GetdepartmentList(Marisfrolg.Fee.EnterpriceService.GetdepartmentListRequest request) {
            return base.Channel.GetdepartmentList(request);
        }
        
        public string GetdepartmentList(string identify, int id) {
            Marisfrolg.Fee.EnterpriceService.GetdepartmentListRequest inValue = new Marisfrolg.Fee.EnterpriceService.GetdepartmentListRequest();
            inValue.Body = new Marisfrolg.Fee.EnterpriceService.GetdepartmentListRequestBody();
            inValue.Body.identify = identify;
            inValue.Body.id = id;
            Marisfrolg.Fee.EnterpriceService.GetdepartmentListResponse retVal = ((Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap)(this)).GetdepartmentList(inValue);
            return retVal.Body.GetdepartmentListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Marisfrolg.Fee.EnterpriceService.CreatedepartmentResponse Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap.Createdepartment(Marisfrolg.Fee.EnterpriceService.CreatedepartmentRequest request) {
            return base.Channel.Createdepartment(request);
        }
        
        public int Createdepartment(string identify, string name, int parentid) {
            Marisfrolg.Fee.EnterpriceService.CreatedepartmentRequest inValue = new Marisfrolg.Fee.EnterpriceService.CreatedepartmentRequest();
            inValue.Body = new Marisfrolg.Fee.EnterpriceService.CreatedepartmentRequestBody();
            inValue.Body.identify = identify;
            inValue.Body.name = name;
            inValue.Body.parentid = parentid;
            Marisfrolg.Fee.EnterpriceService.CreatedepartmentResponse retVal = ((Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap)(this)).Createdepartment(inValue);
            return retVal.Body.CreatedepartmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Marisfrolg.Fee.EnterpriceService.UpdatedepartmentResponse Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap.Updatedepartment(Marisfrolg.Fee.EnterpriceService.UpdatedepartmentRequest request) {
            return base.Channel.Updatedepartment(request);
        }
        
        public int Updatedepartment(string identify, string name, int parentid, int order, int id) {
            Marisfrolg.Fee.EnterpriceService.UpdatedepartmentRequest inValue = new Marisfrolg.Fee.EnterpriceService.UpdatedepartmentRequest();
            inValue.Body = new Marisfrolg.Fee.EnterpriceService.UpdatedepartmentRequestBody();
            inValue.Body.identify = identify;
            inValue.Body.name = name;
            inValue.Body.parentid = parentid;
            inValue.Body.order = order;
            inValue.Body.id = id;
            Marisfrolg.Fee.EnterpriceService.UpdatedepartmentResponse retVal = ((Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap)(this)).Updatedepartment(inValue);
            return retVal.Body.UpdatedepartmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Marisfrolg.Fee.EnterpriceService.DeletedepartmentResponse Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap.Deletedepartment(Marisfrolg.Fee.EnterpriceService.DeletedepartmentRequest request) {
            return base.Channel.Deletedepartment(request);
        }
        
        public int Deletedepartment(string identify, int id) {
            Marisfrolg.Fee.EnterpriceService.DeletedepartmentRequest inValue = new Marisfrolg.Fee.EnterpriceService.DeletedepartmentRequest();
            inValue.Body = new Marisfrolg.Fee.EnterpriceService.DeletedepartmentRequestBody();
            inValue.Body.identify = identify;
            inValue.Body.id = id;
            Marisfrolg.Fee.EnterpriceService.DeletedepartmentResponse retVal = ((Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap)(this)).Deletedepartment(inValue);
            return retVal.Body.DeletedepartmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Marisfrolg.Fee.EnterpriceService.CreateMemberResponse Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap.CreateMember(Marisfrolg.Fee.EnterpriceService.CreateMemberRequest request) {
            return base.Channel.CreateMember(request);
        }
        
        public int CreateMember(string identify, string userid, string name, string department, string position, string mobile, string gender, string email, string weixinid, string avatar_mediaid, string extattr) {
            Marisfrolg.Fee.EnterpriceService.CreateMemberRequest inValue = new Marisfrolg.Fee.EnterpriceService.CreateMemberRequest();
            inValue.Body = new Marisfrolg.Fee.EnterpriceService.CreateMemberRequestBody();
            inValue.Body.identify = identify;
            inValue.Body.userid = userid;
            inValue.Body.name = name;
            inValue.Body.department = department;
            inValue.Body.position = position;
            inValue.Body.mobile = mobile;
            inValue.Body.gender = gender;
            inValue.Body.email = email;
            inValue.Body.weixinid = weixinid;
            inValue.Body.avatar_mediaid = avatar_mediaid;
            inValue.Body.extattr = extattr;
            Marisfrolg.Fee.EnterpriceService.CreateMemberResponse retVal = ((Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap)(this)).CreateMember(inValue);
            return retVal.Body.CreateMemberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Marisfrolg.Fee.EnterpriceService.UpdateMemberResponse Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap.UpdateMember(Marisfrolg.Fee.EnterpriceService.UpdateMemberRequest request) {
            return base.Channel.UpdateMember(request);
        }
        
        public int UpdateMember(string identify, string userid, string name, string department, string position, string mobile, string gender, string email, string weixinid, string enable, string avatar_mediaid, string extattr) {
            Marisfrolg.Fee.EnterpriceService.UpdateMemberRequest inValue = new Marisfrolg.Fee.EnterpriceService.UpdateMemberRequest();
            inValue.Body = new Marisfrolg.Fee.EnterpriceService.UpdateMemberRequestBody();
            inValue.Body.identify = identify;
            inValue.Body.userid = userid;
            inValue.Body.name = name;
            inValue.Body.department = department;
            inValue.Body.position = position;
            inValue.Body.mobile = mobile;
            inValue.Body.gender = gender;
            inValue.Body.email = email;
            inValue.Body.weixinid = weixinid;
            inValue.Body.enable = enable;
            inValue.Body.avatar_mediaid = avatar_mediaid;
            inValue.Body.extattr = extattr;
            Marisfrolg.Fee.EnterpriceService.UpdateMemberResponse retVal = ((Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap)(this)).UpdateMember(inValue);
            return retVal.Body.UpdateMemberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Marisfrolg.Fee.EnterpriceService.DeleteMemberResponse Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap.DeleteMember(Marisfrolg.Fee.EnterpriceService.DeleteMemberRequest request) {
            return base.Channel.DeleteMember(request);
        }
        
        public int DeleteMember(string identify, int userid) {
            Marisfrolg.Fee.EnterpriceService.DeleteMemberRequest inValue = new Marisfrolg.Fee.EnterpriceService.DeleteMemberRequest();
            inValue.Body = new Marisfrolg.Fee.EnterpriceService.DeleteMemberRequestBody();
            inValue.Body.identify = identify;
            inValue.Body.userid = userid;
            Marisfrolg.Fee.EnterpriceService.DeleteMemberResponse retVal = ((Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap)(this)).DeleteMember(inValue);
            return retVal.Body.DeleteMemberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Marisfrolg.Fee.EnterpriceService.BatchDeleteMemberResponse Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap.BatchDeleteMember(Marisfrolg.Fee.EnterpriceService.BatchDeleteMemberRequest request) {
            return base.Channel.BatchDeleteMember(request);
        }
        
        public int BatchDeleteMember(string identify, string useridlist) {
            Marisfrolg.Fee.EnterpriceService.BatchDeleteMemberRequest inValue = new Marisfrolg.Fee.EnterpriceService.BatchDeleteMemberRequest();
            inValue.Body = new Marisfrolg.Fee.EnterpriceService.BatchDeleteMemberRequestBody();
            inValue.Body.identify = identify;
            inValue.Body.useridlist = useridlist;
            Marisfrolg.Fee.EnterpriceService.BatchDeleteMemberResponse retVal = ((Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap)(this)).BatchDeleteMember(inValue);
            return retVal.Body.BatchDeleteMemberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Marisfrolg.Fee.EnterpriceService.GetuseridInfoResponse Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap.GetuseridInfo(Marisfrolg.Fee.EnterpriceService.GetuseridInfoRequest request) {
            return base.Channel.GetuseridInfo(request);
        }
        
        public string GetuseridInfo(string identify, string userid) {
            Marisfrolg.Fee.EnterpriceService.GetuseridInfoRequest inValue = new Marisfrolg.Fee.EnterpriceService.GetuseridInfoRequest();
            inValue.Body = new Marisfrolg.Fee.EnterpriceService.GetuseridInfoRequestBody();
            inValue.Body.identify = identify;
            inValue.Body.userid = userid;
            Marisfrolg.Fee.EnterpriceService.GetuseridInfoResponse retVal = ((Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap)(this)).GetuseridInfo(inValue);
            return retVal.Body.GetuseridInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Marisfrolg.Fee.EnterpriceService.getdepartmenuserResponse Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap.getdepartmenuser(Marisfrolg.Fee.EnterpriceService.getdepartmenuserRequest request) {
            return base.Channel.getdepartmenuser(request);
        }
        
        public string getdepartmenuser(string identify, string department_id, string fetch_child, string status) {
            Marisfrolg.Fee.EnterpriceService.getdepartmenuserRequest inValue = new Marisfrolg.Fee.EnterpriceService.getdepartmenuserRequest();
            inValue.Body = new Marisfrolg.Fee.EnterpriceService.getdepartmenuserRequestBody();
            inValue.Body.identify = identify;
            inValue.Body.department_id = department_id;
            inValue.Body.fetch_child = fetch_child;
            inValue.Body.status = status;
            Marisfrolg.Fee.EnterpriceService.getdepartmenuserResponse retVal = ((Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap)(this)).getdepartmenuser(inValue);
            return retVal.Body.getdepartmenuserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Marisfrolg.Fee.EnterpriceService.getdepartmenuserinfoResponse Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap.getdepartmenuserinfo(Marisfrolg.Fee.EnterpriceService.getdepartmenuserinfoRequest request) {
            return base.Channel.getdepartmenuserinfo(request);
        }
        
        public string getdepartmenuserinfo(string identify, string department_id, string fetch_child, string status) {
            Marisfrolg.Fee.EnterpriceService.getdepartmenuserinfoRequest inValue = new Marisfrolg.Fee.EnterpriceService.getdepartmenuserinfoRequest();
            inValue.Body = new Marisfrolg.Fee.EnterpriceService.getdepartmenuserinfoRequestBody();
            inValue.Body.identify = identify;
            inValue.Body.department_id = department_id;
            inValue.Body.fetch_child = fetch_child;
            inValue.Body.status = status;
            Marisfrolg.Fee.EnterpriceService.getdepartmenuserinfoResponse retVal = ((Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap)(this)).getdepartmenuserinfo(inValue);
            return retVal.Body.getdepartmenuserinfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Marisfrolg.Fee.EnterpriceService.GetticketResponse Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap.Getticket(Marisfrolg.Fee.EnterpriceService.GetticketRequest request) {
          
            return base.Channel.Getticket(request);
        }
        
        public string Getticket(string identify) {
            Marisfrolg.Fee.EnterpriceService.GetticketRequest inValue = new Marisfrolg.Fee.EnterpriceService.GetticketRequest();
            inValue.Body = new Marisfrolg.Fee.EnterpriceService.GetticketRequestBody();
            inValue.Body.identify = identify;
            Marisfrolg.Fee.EnterpriceService.GetticketResponse retVal = ((Marisfrolg.Fee.EnterpriceService.MfWeiXinEmpServiceSoap)(this)).Getticket(inValue);
            return retVal.Body.GetticketResult;
        }
    }
}
